name: dp-services

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py
          **/requirements.txt
          **/constraints.txt
    - name: pip-install
      run: make install
    - name: unit-tests
      run: make test
